spring.application.name=telekom-aktivasyon
spring.datasource.url=jdbc:postgresql://localhost:5432/telekom_aktivasyon
spring.datasource.username=sezin
spring.datasource.password=
spring.jpa.properties.hibernate.default_schema=telekom
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true